### PR TITLE
Update to latest ActiveMerchant master

### PR DESCRIPTION
**Pull request by isikyus**
To pull in the new CA certificate file, since the current one doesn't work with eWay Sandbox as of lat week.

We don't _need_ all the other changes, but it's probably best to pull them in anyway for security's sake.

### CODE REVIEW

**Comment by isikyus** [comment]
https://github.com/Birdsnest/active_merchant/pull/1/files#diff-d3bb3391c79904494c60ee2ac2f33070 may be useful as a summary of the changes here.

**Comment by isikyus** [comment]
[Update ActiveMerchant to fix eWay on Staging (was: Staging Armadillo unable to connect to eWay for credit card payments)](https://trello.com/c/kPdOPAuN/499-update-activemerchant-to-fix-eway-on-staging-was-staging-armadillo-unable-to-connect-to-eway-for-credit-card-payments)

**Comment by isikyus** [comment]
I believe we can ignore the CircleCI failure, since it looks like ActiveMerchant isn't actually using CircleCI any more. Note that they have only a Travis CI badge: https://github.com/activemerchant/active_merchant/blob/master/README.md

**Comment by keithpitty** [comment]
@isikyus is this ready for review or would you prefer to fix the Travis build failures and remove the CircleCI build?

**Comment by isikyus** [comment]
> @isikyus is this ready for review or would you prefer to fix the Travis build failures and remove the CircleCI build?

I'd prefer to fix the build failures first; I made the mistake of requesting review before I checked the CI builds were working.

However, as this work now has a ticket I'd like to wait and see how the ticket is prioritised before picking this up again.

**Comment by keithpitty** [comment]
@isikyus it looks like Travis is reporting a unit test error.

**Comment by isikyus** [comment]
The Travis error is specifically on Ruby 2.4 and Rails 4.1 (https://travis-ci.com/Birdsnest/active_merchant/jobs/162541006) -- all other builds are passing.

I've started looking into it now, but it looks like it's a finicky gem version error that could take some time to fix. Given that we don't immediately need Ruby 2.4 support, I'm wondering if we should just exclude that particular Ruby/Rails combination.

In the meantime I'll keep looking for a fix that involves the minimum of other gem changes.

**Comment by keithpitty** [comment]
> The Travis error is specifically on Ruby 2.4 and Rails 4.1 (https://travis-ci.com/Birdsnest/active_merchant/jobs/162541006) -- all other builds are passing.
> 
> I've started looking into it now, but it looks like it's a finicky gem version error that could take some time to fix. Given that we don't immediately need Ruby 2.4 support, I'm wondering if we should just exclude that particular Ruby/Rails combination.
> 
> In the meantime I'll keep looking for a fix that involves the minimum of other gem changes.

Fair point. I agree that we should be pragmatic about this. I can see that the build for Ruby 2.3 and Rails 4.1 passes so I'm happy for the failing build to be excluded.

**Review by keithpitty — APPROVED** [review]
Now that the Travis build passes, I'm happy to approve this PR. 👍

**Pull request merged**
